runtime: python39
entrypoint: gunicorn -b :$PORT imagegen.wsgi
env_variables:
  DJANGO_SETTINGS_MODULE: "myproject.settings"
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto